import type { Project, Template, GenerationRecord } from "./store";

export const mockTemplates: Template[] = [
  {
    id: "tpl-1",
    name: "电商商品主图",
    description: "一键生成高质量电商商品展示图，支持多种风格和背景",
    category: "电商",
    thumbnail: "/placeholder.svg",
    models: ["FLUX.1", "SDXL"],
    tags: ["电商", "商品图", "白底图"],
  },
  {
    id: "tpl-2",
    name: "社交媒体封面",
    description: "快速生成适配各平台尺寸的社交媒体封面图",
    category: "社交媒体",
    thumbnail: "/placeholder.svg",
    models: ["FLUX.1"],
    tags: ["封面", "小红书", "抖音"],
  },
  {
    id: "tpl-3",
    name: "短视频片头",
    description: "AI 生成短视频开场动画，多种风格可选",
    category: "视频",
    thumbnail: "/placeholder.svg",
    models: ["Kling", "FLUX.1"],
    tags: ["视频", "片头", "动画"],
  },
  {
    id: "tpl-4",
    name: "品牌广告海报",
    description: "输入品牌信息和风格，生成专业广告海报",
    category: "广告",
    thumbnail: "/placeholder.svg",
    models: ["SDXL", "FLUX.1"],
    tags: ["广告", "海报", "品牌"],
  },
  {
    id: "tpl-5",
    name: "分镜脚本可视化",
    description: "将文字脚本转化为分镜画面，快速预览影片效果",
    category: "影视",
    thumbnail: "/placeholder.svg",
    models: ["FLUX.1", "SDXL"],
    tags: ["分镜", "影视", "脚本"],
  },
  {
    id: "tpl-6",
    name: "AI 写真照",
    description: "上传参考图，生成多种风格的 AI 写真",
    category: "人像",
    thumbnail: "/placeholder.svg",
    models: ["FLUX.1"],
    tags: ["写真", "人像", "风格化"],
  },
  {
    id: "tpl-7",
    name: "Logo 概念设计",
    description: "输入品牌名称和调性，生成多组 Logo 概念方案",
    category: "设计",
    thumbnail: "/placeholder.svg",
    models: ["SDXL"],
    tags: ["Logo", "设计", "品牌"],
  },
  {
    id: "tpl-8",
    name: "产品宣传视频",
    description: "从产品图自动生成短视频宣传片",
    category: "视频",
    thumbnail: "/placeholder.svg",
    models: ["Kling"],
    tags: ["视频", "宣传", "产品"],
  },
  {
    id: "tpl-9",
    name: "插画风格转换",
    description: "将照片或图片转换为插画、水彩、油画等艺术风格",
    category: "设计",
    thumbnail: "/placeholder.svg",
    models: ["SDXL", "FLUX.1"],
    tags: ["插画", "风格转换", "艺术"],
  },
  {
    id: "tpl-10",
    name: "电商详情页组图",
    description: "批量生成电商详情页场景图和细节图",
    category: "电商",
    thumbnail: "/placeholder.svg",
    models: ["FLUX.1", "SDXL"],
    tags: ["电商", "详情页", "批量"],
  },
  {
    id: "tpl-11",
    name: "YouTube 缩略图",
    description: "生成高点击率的 YouTube 视频缩略图",
    category: "社交媒体",
    thumbnail: "/placeholder.svg",
    models: ["FLUX.1"],
    tags: ["YouTube", "缩略图", "封面"],
  },
  {
    id: "tpl-12",
    name: "概念艺术场景",
    description: "生成影视级概念艺术场景图，适合创意探索",
    category: "影视",
    thumbnail: "/placeholder.svg",
    models: ["SDXL", "FLUX.1"],
    tags: ["概念艺术", "场景", "影视"],
  },
];

export const mockProjects: Project[] = [
  {
    id: "proj-1",
    name: "春季新品推广",
    description: "2026 春季新品电商主图和详情页",
    thumbnail: "/placeholder.svg",
    updatedAt: "2026-03-25",
    status: "active",
  },
  {
    id: "proj-2",
    name: "品牌宣传视频",
    description: "品牌年度宣传短视频制作",
    thumbnail: "/placeholder.svg",
    updatedAt: "2026-03-24",
    status: "draft",
  },
  {
    id: "proj-3",
    name: "小红书内容矩阵",
    description: "小红书图文内容批量生成",
    thumbnail: "/placeholder.svg",
    updatedAt: "2026-03-22",
    status: "active",
  },
];

export const mockExploreWorks = [
  {
    id: "work-1",
    title: "赛博朋克城市",
    author: "创意达人A",
    thumbnail: "/api/placeholder?w=512&h=512&style=landscape&seed=cyberpunk-city",
    likes: 328,
    category: "概念艺术",
    prompt: "A cyberpunk city at night with neon lights and flying cars, rain-soaked streets, blade runner style",
    model: "FLUX.1",
  },
  {
    id: "work-2",
    title: "春日和风插画",
    author: "插画师B",
    thumbnail: "/api/placeholder?w=512&h=512&style=waves&seed=spring-illustration",
    likes: 256,
    category: "插画",
    prompt: "Japanese spring illustration, cherry blossoms, watercolor style, peaceful garden",
    model: "SDXL",
  },
  {
    id: "work-3",
    title: "极简产品摄影",
    author: "电商运营C",
    thumbnail: "/api/placeholder?w=512&h=512&style=geometric&seed=product-photo",
    likes: 189,
    category: "电商",
    prompt: "Minimalist product photography, wireless earbuds on white marble, soft studio lighting",
    model: "FLUX.1",
  },
  {
    id: "work-4",
    title: "奇幻森林短片",
    author: "影视工作室D",
    thumbnail: "/api/placeholder?w=512&h=512&style=landscape&seed=fantasy-forest",
    likes: 412,
    category: "视频",
    prompt: "Enchanted forest with glowing mushrooms and fireflies, cinematic drone shot",
    model: "Kling",
  },
  {
    id: "work-5",
    title: "复古胶片人像",
    author: "摄影师E",
    thumbnail: "/api/placeholder?w=512&h=512&style=abstract&seed=vintage-portrait",
    likes: 167,
    category: "人像",
    prompt: "Vintage film portrait, warm golden hour light, 35mm grain, nostalgic mood",
    model: "FLUX.1",
  },
  {
    id: "work-6",
    title: "国潮品牌海报",
    author: "设计师F",
    thumbnail: "/api/placeholder?w=512&h=512&style=geometric&seed=guochao-poster",
    likes: 293,
    category: "广告",
    prompt: "Chinese style brand poster, red and gold colors, modern fusion of traditional elements",
    model: "SDXL",
  },
  {
    id: "work-7",
    title: "未来建筑概念",
    author: "建筑师G",
    thumbnail: "/api/placeholder?w=512&h=512&style=landscape&seed=future-architecture",
    likes: 345,
    category: "概念艺术",
    prompt: "Futuristic architecture concept, organic curves, glass and greenery, utopian city",
    model: "FLUX.1",
  },
  {
    id: "work-8",
    title: "美食短视频",
    author: "美食博主H",
    thumbnail: "/api/placeholder?w=512&h=512&style=waves&seed=food-video",
    likes: 521,
    category: "视频",
    prompt: "Slow motion food video, pouring chocolate on strawberries, macro shot",
    model: "Kling",
  },
  {
    id: "work-9",
    title: "星空延时摄影",
    author: "旅行者I",
    thumbnail: "/api/placeholder?w=512&h=512&style=abstract&seed=starry-night",
    likes: 487,
    category: "概念艺术",
    prompt: "Milky way timelapse over desert landscape, astrophotography, long exposure",
    model: "FLUX.1",
  },
  {
    id: "work-10",
    title: "潮玩手办渲染",
    author: "3D艺术家J",
    thumbnail: "/api/placeholder?w=512&h=512&style=geometric&seed=toy-render",
    likes: 234,
    category: "电商",
    prompt: "Designer toy figure 3D render, cute character, soft pastel colors, studio lighting",
    model: "SDXL",
  },
  {
    id: "work-11",
    title: "水墨山水动画",
    author: "动画师K",
    thumbnail: "/api/placeholder?w=512&h=512&style=waves&seed=ink-landscape",
    likes: 378,
    category: "视频",
    prompt: "Chinese ink wash painting animation, mountains and rivers, flowing clouds, zen atmosphere",
    model: "Kling",
  },
  {
    id: "work-12",
    title: "霓虹街头涂鸦",
    author: "街头艺术家L",
    thumbnail: "/api/placeholder?w=512&h=512&style=abstract&seed=neon-graffiti",
    likes: 445,
    category: "插画",
    prompt: "Neon street art graffiti, vibrant colors, urban wall, hip hop culture",
    model: "FLUX.1",
  },
];

export const mockHistory: GenerationRecord[] = [
  {
    id: "gen-1",
    projectId: "proj-1",
    type: "image",
    prompt: "春季新品白底展示图，简约风格",
    model: "FLUX.1",
    outputUrl: "/placeholder.svg",
    createdAt: "2026-03-25 14:30",
    status: "success",
  },
  {
    id: "gen-2",
    projectId: "proj-1",
    type: "image",
    prompt: "春季新品场景图，户外阳光",
    model: "SDXL",
    outputUrl: "/placeholder.svg",
    createdAt: "2026-03-25 14:25",
    status: "success",
  },
  {
    id: "gen-3",
    projectId: "proj-2",
    type: "video",
    prompt: "品牌 Logo 动画展示，科技感",
    model: "Kling",
    outputUrl: "/placeholder.svg",
    createdAt: "2026-03-24 16:10",
    status: "success",
  },
  {
    id: "gen-4",
    projectId: "proj-3",
    type: "image",
    prompt: "小红书风格美妆产品图",
    model: "FLUX.1",
    outputUrl: "/placeholder.svg",
    createdAt: "2026-03-22 10:45",
    status: "failed",
  },
];
